### ISSUE TITLE
Kdump service fails to start if the crashkernel command-line argument is absent in fadump case

### ISSUE THREAD

**Issue by sourabhjains** [rhkdump/kdump-utils#35]
Fadump reserves memory regardless of whether the crashkernel parameter is passed to the production kernel. Therefore, the expectation is that the kdump service should not depend on the crashkernel command-line argument when fadump is being used.

The patch that made the kdump service dependent on the crashkernel kernel command-line parameter is: https://github.com/rhkdump/kdump-utils/commit/0084806493d01d14dc7148b2dd5fc46e07b42c96.

The above commit did not take into account that fadump uses the kdump service, but crashkernel is not mandatory for fadump to reserve memory.

Any suggestions on how to remove the dependency on the crashkernel kernel parameter for the kdump service when fadump is active?

**Comment by sourabhjains** [comment]
Any input on how to fix this issue?

Didn't find a way to restrict ConditionKernelCommandLine condition for only kdump.

**Comment by liutgnu** [comment]
Hi @sourabhjains ,

Thanks for the issue, currently the maintainers are all in holiday until Oct 7. So it may take a few days before their reply. By a quick glimpse, I think it is a bug and should be fixed. I will take it a look tomorrow and try to give it a shot.

Thanks,
Tao Liu

**Comment by liutgnu** [comment]
I guess what we want, is something like:

ConditionKernelCommandLine=crashkernel|fadump

But it is hard to implement the "OR" operation for the 2 strings. Though chatgpt can give a complicated way to implememt OR conditions.

I don't have further suggestions, see how other people think of it, or we just revert the 0084806 commit?

**Comment by sourabhjains** [comment]
Hello @liutgnu 

Thanks for providing input on the issue.

> I guess what we want, is something like:
> 
> ConditionKernelCommandLine=crashkernel|fadump
> 
> But it is hard to implement the "OR" operation for the 2 strings. Though chatgpt can give a complicated way to implememt OR conditions.

Yes there is no native support to add conditions to ConditionKernelCommandLine. 

> 
> I don't have further suggestions, see how other people think of it, or we just revert the [0084806](https://github.com/rhkdump/kdump-utils/pull/39) commit?

Reverting https://github.com/rhkdump/kdump-utils/commit/0084806493d01d14dc7148b2dd5fc46e07b42c96 is fine because kdump scripts has checks for memory reservation.

But we care early kdump service exit if crashkernel is not present in kernel command-line then how about 
https://github.com/rhkdump/kdump-utils/pull/39  ?
